config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :sessions
  root 'pages#home'
  resources :infos
  resources :users, except: [:new]

end

app/models/info.rb
class Info < ActiveRecord::Base
  belongs_to :user
  validates :site, presence: true
  validates :username, presence: true, length: {minimum: 4, maximum: 50}
  validates :password, presence: true, length: {minimum: 4}
  validates :signature, presence: true, length: {minimum: 3}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = {0 => :user}
  attr_reader :role
    def initialize(role_id = 0)
      @role = ROLES[0]
    end

    def role?(role_name)
      role == role_name
    end
    
  has_secure_password
  has_many :info
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :user, presence: true, uniqueness: {case_sensitive: false}, length:{minimum: 3, maximum: 25}
  validates :email, presence: true, length: {maximum: 105}, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}
  before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
    flash[:danger] = "You must be logged in to perform that action"
    redirect_to root_path
   end
  end

  helper_method :current_user, :logged_in?
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  def new
    @info = Info.new
  end

  def destroy
    @info = Info.find(params[:id])
    @info.destroy
      flash[:notice] = "The information is successfully deleted"
      redirect_to infos_path(@info)
  end

  def show
    @info = Info.find(params[:id])
  end

  def index
    @infos = Info.all
  end

  def edit
    @info = Info.find(params[:id])
  end

  def update
    @info = Info.find(params[:id])
    if @info.update(info_params)
      flash[:success] = "The information was successfully updated"
      redirect_to info_path(@info)
    else
      flash[:success] = "Unable to update the information !!!"
      render 'edit'
    end
  end

  def create
    @info = Info.new(info_params)
    @info.user  = User.first
    if @info.save
      flash[:success] = "The information was successfully saved"
      redirect_to info_path(@info)
    else
      render 'new'
    end
  end

  private
  def info_params
    params.require(:info).permit(:site, :username, :password, :signature)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def update
    id = params[:id].to_i
    session[:id] = User::ROLES.has_key?(id) ? id : 0
    flash[:success] = "New role #{User::ROLES[id]} was set!"
    redirect_to root_path
  end
  
  def create
    user = User.find_by(user: params[:session][:user].downcase)
    if user  && user.authenticate(params[:session][:password])
     session[:user_id] = user.id
     flash[:success] = "You have logged in"
     redirect_to users_path(user)
    else
     flash.now[:danger] = "There was something wrong with your login information"
     render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome #{@user.user}"
      redirect_to infos_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Your account was successfully updated"
      redirect_to infos_path
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:user, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/infos/_form.html.erb
<div align = "center">
<%= form_for @info do |f| %>
  <p>
  <%= f.label :site, class: "site-field"%>
  <%= f.text_field :site%><br>
  </p>
  <p>
  <%= f.label :username, class: "username-field"%>
  <%= f.text_field :username%><br>
 </p>
  <%= f.label :password, class: "password-field"%>
  <%= f.text_field :password%><br>
  <p>
  <%= f.label :signature, class: "signature-field"%>
  <%= f.text_field :signature%><br>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>
<% if @info.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(@info.errors.count, "error") %>
      prohibited this article from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% @info.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/infos/edit.html.erb
<p align="center" style="margin: 70px auto;"><font size="4"><em><u>Please Edit the information if desired!!</u></em></font></p>

<%= render 'form'%>

app/views/infos/index.html.erb
<div align="center" >
<h1><b><em>Your List</em></b></h1>
</div>
<body>
<table style="width:70%; margin: 115px auto;" cellspacing="30px" style="height:136px;">
  <tr>
    <th>Site Name</th>
    <th>Username</th>
    <th>Password</th>
    <th>Signature</th>
  </tr>
  <% @infos.each do |info|%>
  <tr>
    <td><%= info.site%></td>
    <td><%= info.username[0,3] + "****"%></td>
    <td><%= "******"%></td>
    <td><%= info.signature%></td>
    <td><%= link_to 'Edit', edit_info_path(info), class: "btn btn-xs btn-primary"%></td>
    <td><%= link_to 'Show', info_path(info), class: "btn btn-xs btn-primary"%></td>
    <td><%= link_to 'Delete', info_path(info), method: :delete, data: {confirm: "Are you sure you want to delete the information?"}, class: "btn btn-xs btn-danger" %></td>
  </tr>
  <%end%>
</table>
<style>
  table, th, td{
  border: 2px solid blue;
  text-align: center;
}
</style>

</body>

app/views/infos/new.html.erb
<div align="center">
<h1>Store Information!!</h1>
</div>
<%= render 'form'%>

app/views/infos/show.html.erb
<div align="center">
<p><b><font color="red">The following information was added</font></b></p>
<body>
<p>
  <b>Site Name:</b> <%= @info.site %>
</p>

<p>
  <b>Username:</b> <%= @info.username %>
</p>

<p>
  <b>Password:</b> <%= @info.password %>
</p>

<p>
  <b>Signature:</b> <%= @info.signature %>
</p>
</div>
</body>

app/views/layouts/_buttons.html.erb
<body>
<ul class="nav nav-pills" style="width:70%; margin-left: 200px;" >
  <li><%= link_to "Home", root_path, class: "active", id: "logo", role: "presentation"%></li>
  <li><%= link_to "Add-Info", new_info_path, class: "add-info"%></li>
  <li><%= link_to "View-Info", infos_path, class: "view-info"%></li>
</ul>
<ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
          <% else %>
          <% end %>
      </ul>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>One2many</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/buttons'%>
</head>
<body>
<div class="row">
 <div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>'>
   <a href="#" class="close" data-dismiss="alert">&#215;</a>
   <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>
 </div>
</div>
  <%= yield %>

</body>
<style>
  body{
    background-color: #cccccc;
  }
</style>
</html>

app/views/pages/home.html.erb
<h1 id="test" style="margin-top: 100px;"><font color="blue">Welcome!!</font></h1>
<div style="margin: 200px; margin-left: 350px;">
<p><font size="5"><em>
  <font color="red">One2Many</font> is a simple web application which helps you store all your important digital information. This <font color="blue">"One"</font> directory can help store <font color="blue">"Many"</font> of your confidential data/information.
</em></font></p>

<p>
  <u>The application can be well used in the following scenarios:</u>
  <ul>
    <li>Track your important <b>login</b> details across various web platforms</li>
    <li>Store important banking details(example:<em> username and password</em>).</li>
    <li>If you often tend to forget your important <b>digital</b> details then just avail from this application.</li>
  </ul>
</p>
</div>

app/views/shared/_list.html.erb
<div align="center" >
<h1><b><em>Your List</em></b></h1>
</div>
<body>
<table style="width:70%; margin: 115px auto;" cellspacing="30px" style="height:136px;">
  <tr>
    <th>Site Name</th>
    <th>Username</th>
    <th>Password</th>
    <th>Signature</th>
  </tr>
  <% obj.each do |info|%>
  <tr>
    <td><%= info.site%></td>
    <td><%= info.username[0,3] + "****"%></td>
    <td><%= "******"%></td>
    <td><%= info.signature%></td>
    <td><%= link_to 'Edit', edit_info_path(info), class: "btn btn-xs btn-primary"%></td>
    <td><%= link_to 'Show', info_path(info), class: "btn btn-xs btn-primary"%></td>
    <td><%= link_to 'Delete', info_path(info), method: :delete, data: {confirm: "Are you sure you want to delete the information?"}, class: "btn btn-xs btn-danger" %></td>
  </tr>
  <%end%>
</table>
<style>
  table, th, td{
  border: 2px solid blue;
  text-align: center;
}
</style>

</body>

app/views/users/_form.html.erb
<div align = "center">
<%= form_for @user do |f| %>
  <p>
  <%= f.label :user, class: "site-field"%>
  <%= f.text_field :user%><br>
  </p>
  <p>
  <%= f.label :email, class: "username-field"%>
  <%= f.text_field :email%><br>
 </p>
  <%= f.label :password, class: "password-field"%>
  <%= f.text_field :password%><br>
  <p>
    <%= f.submit(@user.new_record? ? "Sign Up" : "Update Acount", class: 'btn btn-primary btn-large') %>
  </p>
<% end %>
</div>
<% if @user.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this article from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% @user.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/users/edit.html.erb
<h1 align="center">Edit User Account</h1>
<%= render 'form' %>

app/views/users/new.html.erb
<h1 align="center">Signup</h1>
<%= render 'form' %>